[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "mira"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastmcp==2.14.3",
  "pefile==2024.8.26",
  "capstone==5.0.6",
  "yara-python==4.5.4",
  "flare-capa==9.1.0",
]

[tool.setuptools.packages.find]
include = ["mira*"]
